syntax = "proto3";

package classicfarm.ws.v1.reason;

option go_package = "github.com/Wriosley/supernova-classic-farm/server/gen/classicfarm/v1/ws/reason;reasonv1";

enum StateChangeReason {
  STATE_CHANGE_REASON_UNSPECIFIED = 0;
  BUY_SEEDS = 1;
  PLANT = 2;
  APPLY_FERTILIZER = 3;
  MATURED = 4;
  HARVEST = 5;
  CLEAN_PLOT = 6;
  SELL_CROP = 7;
  CLAIM_CHAPTER_REWARD = 8;
  BUY_FERTILIZER = 9;
  FRIEND_STEAL = 10;
  APPLY_PEST_TO_FRIEND = 11;
  CATCH_PEST_FOR_FRIEND = 12;
  CATCH_PEST = 13;
}
